### ISSUE TITLE
Header image stays the same between games

### ISSUE THREAD

**Issue by jam3shug** [Shock9616/Phoenix#2]
The header image stays the same when switching between games

https://user-images.githubusercontent.com/72482214/210274927-f1c83ea1-be3c-482f-8306-4d2bae7dbf3b.mov

**Comment by Shock9616** [comment]
Thank you for reporting this bug! I have actually already found and fixed this issue, so when the next release comes out it will be fixed.

The problem is caused by the way I had the edit function working. The images are copied into a cachedImages folder and the copies are named `<game_name>_header.png` (or .jpg as the case may be). The problem was that the game's name was coming from the name input field, which if you didn't edit it would be blank so every edited image was ending up being called `_header.png` instead of a unique name.

The good news is that until the next release comes out, there's an easy workaround. Any time you change a header image or icon, just put the game's name in the name field as well and the issue will be resolved

I'm sorry for the inconvenience, and I hope that you've been enjoying the app otherwise 🙂

**Comment by jam3shug** [comment]
I have been enjoying the app! Thx for the help.

**Comment by Shock9616** [comment]
No problem!
